name: release-ci

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x64
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set Git Config
        run: |
          echo "set some necessary env-vars"
          git config user.name "GHA Bot"
          git config user.email "actions@users.noreply.github.com"
      - name: Restore maven .m2
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Generate mvn settings xml
        uses: s4u/maven-settings-action@v2.1.1
        with:
          servers: '[{"id": "maven.jenkins-ci.org", "username": "${{ secrets.JENKINS_CI_USERNAME }}", "password": "${{ secrets.JENKINS_CI_PASSWORD }}"}]'
      - name: Build and invoke integration test HPI
        run: ./mvnw install
#        run: ./mvnw install -Pit
      - name: Prepare for release
        run: echo -ne '\n' | ./mvnw gitflow:release-start gitflow:release-finish
